name: CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

env:
  # https://github.com/actions/virtual-environments/tree/main/images/macos
  DEVELOPER_DIR: /Applications/Xcode_12.3.app/Contents/Developer

  IOS_SDK: iphonesimulator14.3

  PROJECT: PresenterKit.xcodeproj
  SCHEME: PresenterKit

  EXAMPLE_PROJECT: Example/ExampleApp.xcodeproj
  EXAMPLE_SCHEME: ExampleApp

  IOS_DEST: "OS=14.3,name=iPhone 12 Mini"

jobs:
  job-main:
    name: Build and Test
    runs-on: macOS-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v2

      - name: xcode version
        run: xcodebuild -version -sdk

      - name: list simulators
        run: |
          xcrun simctl delete unavailable
          xcrun simctl list

      - name: unit tests
        run: |
          set -o pipefail
          xcodebuild clean test \
              -project "$PROJECT" \
              -scheme "$SCHEME" \
              -sdk "$IOS_SDK" \
              -destination "$IOS_DEST" \
              ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO | xcpretty -c

      - name: ui tests
        run: |
          set -o pipefail
          xcodebuild clean test \
              -project "$EXAMPLE_PROJECT" \
              -scheme "$EXAMPLE_SCHEME" \
              -sdk "$IOS_SDK" \
              -destination "$IOS_DEST" \
              ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO | xcpretty -c
