name: SwiftPM Integration

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

env:
  # https://github.com/actions/virtual-environments/tree/main/images/macos
  DEVELOPER_DIR: /Applications/Xcode_12.2.app/Contents/Developer

  IOS_SDK: iphonesimulator14.2
  IOS_DEST: "OS=14.2,name=iPhone 12 Mini"

  SCHEME: PresenterKit

jobs:
  job-build:
    name: SwiftPM Build
    runs-on: macOS-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v2

      - name: xcode version
        run: xcodebuild -version -sdk

      - name: list simulators
        run: |
          xcrun simctl delete unavailable
          xcrun simctl list

      - name: generate xcodeproj
        run: swift package generate-xcodeproj

      - name: Build
        run: |
          set -o pipefail
          xcodebuild clean build -scheme "$SCHEME" -sdk "$IOS_SDK" -destination "$IOS_DEST" | xcpretty -c
